Directory:  df_apply_axis
Directory:  data
error parsing directory data, 311-service-requests.csv is not a .ipynb notebook file
============================ 
=== [RUN] RUNNING df_apply_axis === 
=== [RUN] Changing kernel of ../benchmarks/test1/df_apply_axis/df_apply_axis.ipynb to ipyflow
=== [RUN] Changing kernel of ../benchmarks/test1/df_apply_axis/m_df_apply_axis.ipynb to ipyflow
=== [RUN] Found source diff: at cell index: 3 with cell ID: 0a854f03-6764-495c-a8ed-efee504590aa
=== [RUN] Code of original cell 3: 
df = df.apply(np.sum, axis=0)
=== [RUN] Code to be changed into cell 3: 
df = df.apply(np.sum, axis=1) 
Failed to run benchamrk df_apply_axis, with files ../benchmarks/test1/df_apply_axis/df_apply_axis.ipynb and ../benchmarks/test1/df_apply_axis/m_df_apply_axis.ipynb
=== [RUN] COMPLETE RUNNING df_apply_axis ===
============================ 


